In [1]:
# %pip install pandas

In [2]:
import pandas as pd

In [3]:
revenues_per_day = pd.read_csv('../data/revenues_per_day (1).csv')

print(f'Rows: {revenues_per_day.shape[0]}, columns: {revenues_per_day.shape[1]}')
print(revenues_per_day.dtypes)

Rows: 337818, columns: 6
id                 str
date               str
title              str
revenue          int64
theaters       float64
distributor        str
dtype: object

In [4]:
revenues_per_day.head()

,id,date,title,revenue,theaters,distributor
0,8b19ad43-3a7e-b14b-49e9-1f7a0eb1568e,2004-09-20,Sky Captain and the World of Tomorrow,925482,3170.0,Paramount Pictures
1,481fc700-fcdd-1919-c53c-09fcd423a596,2004-09-20,Resident Evil: Apocalypse,643680,3284.0,Screen Gems
2,06719cc2-c05e-8c0b-56b6-b8b13e056509,2004-09-20,Mr 3000,425375,2736.0,Walt Disney Studios Motion Pictures
3,3be8e4a8-2716-00be-80be-eb342ba3cbe7,2004-09-20,Wimbledon,416970,2034.0,Universal Pictures
4,c5f26b59-6a64-ae8e-8f58-7cefb09eadfe,2004-09-20,Cellular,412000,2749.0,New Line Cinema

#### Convert types

In [5]:
revenues_per_day['date'] = pd.to_datetime(revenues_per_day['date'], errors='coerce')

In [6]:
revenues_per_day['theaters'] = pd.to_numeric(revenues_per_day['theaters'], errors='coerce')
revenues_per_day['theaters'] = revenues_per_day['theaters'].round().astype('Int64')

In [7]:
print(revenues_per_day.dtypes)

id                        str
date           datetime64[us]
title                     str
revenue                 int64
theaters                Int64
distributor               str
dtype: object

#### Standardize categorical text

In [8]:
revenues_per_day['title_raw'] = revenues_per_day['title']
revenues_per_day['distributor_raw'] = revenues_per_day['distributor']

In [9]:
revenues_per_day['title'] = revenues_per_day['title'].str.strip().str.lower()

In [10]:
revenues_per_day['distributor'] = revenues_per_day['distributor'].astype('string').str.strip()

In [11]:
revenues_per_day['distributor'] = revenues_per_day['distributor'].mask(
    revenues_per_day['distributor'].isna() | (revenues_per_day['distributor'] == '-') | (revenues_per_day['distributor'] == ''),
    'Unknown'
)

In [12]:
print('Empty titles after strip:', (revenues_per_day['title'].isna() | (revenues_per_day['title'] == '')).sum())
print('Distributor Unknown count:', (revenues_per_day['distributor'] == 'Unknown').sum())
print('Unique titles:', revenues_per_day['title'].nunique(dropna=True))
print('Unique distributors:', revenues_per_day['distributor'].nunique(dropna=True))

Empty titles after strip: 0
Distributor Unknown count: 7644
Unique titles: 6544
Unique distributors: 362

#### Handle missing values

In [13]:
# TODO: missing theaters

In [14]:
print('Nulls per column:')
print(revenues_per_day.isna().sum())

print('Rows with theaters missing and revenue > 0:',
      ((revenues_per_day['theaters'].isna()) & (revenues_per_day['revenue'] > 0)).sum())

Nulls per column:
id                   0
date                 0
title                0
revenue              0
theaters           161
distributor          0
title_raw            0
distributor_raw    225
dtype: int64
Rows with theaters missing and revenue > 0: 159

#### quality checks

In [15]:
print('id unique:', revenues_per_day['id'].is_unique)

id unique: True

In [16]:
print('Revenue < 0:', (revenues_per_day['revenue'] < 0).sum())

Revenue < 0: 0

In [17]:
print('Theaters <= 0:', (revenues_per_day['theaters'].dropna() <= 0).sum())

Theaters <= 0: 0

In [18]:
grain_cols = ['date', 'title', 'distributor']
print('Duplicate rows at grain (date, title, distributor):',
      revenues_per_day.duplicated(subset=grain_cols).sum())

Duplicate rows at grain (date, title, distributor): 0

In [19]:
print(f'Rows after transforms: {len(revenues_per_day)}')

Rows after transforms: 337818

In [20]:
revenues_per_day.head()

,id,date,title,revenue,theaters,distributor,title_raw,distributor_raw
0,8b19ad43-3a7e-b14b-49e9-1f7a0eb1568e,2004-09-20,sky captain and the world of tomorrow,925482,3170,Paramount Pictures,Sky Captain and the World of Tomorrow,Paramount Pictures
1,481fc700-fcdd-1919-c53c-09fcd423a596,2004-09-20,resident evil: apocalypse,643680,3284,Screen Gems,Resident Evil: Apocalypse,Screen Gems
2,06719cc2-c05e-8c0b-56b6-b8b13e056509,2004-09-20,mr 3000,425375,2736,Walt Disney Studios Motion Pictures,Mr 3000,Walt Disney Studios Motion Pictures
3,3be8e4a8-2716-00be-80be-eb342ba3cbe7,2004-09-20,wimbledon,416970,2034,Universal Pictures,Wimbledon,Universal Pictures
4,c5f26b59-6a64-ae8e-8f58-7cefb09eadfe,2004-09-20,cellular,412000,2749,New Line Cinema,Cellular,New Line Cinema